#!/usr/bin/env node
/**
 * Extracts editable JSX from HTML pages (#app-source) and writes
 * precompiled assets/*.js so visitors never download Babel.
 *
 * Edit the <script type="text/jsx" id="app-source"> block in the HTML,
 * then run: npm run build
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import babel from '@babel/core';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');

const targets = [
  { html: 'index.html', out: 'assets/app.js' },
  { html: 'soc-reports.html', out: 'assets/soc-reports.js' },
];

function buildOne({ html, out }) {
  const htmlPath = path.join(root, html);
  const outPath = path.join(root, out);
  const sourceHtml = fs.readFileSync(htmlPath, 'utf8');
  const match = sourceHtml.match(
    /<script\b(?=[^>]*\bid=["']app-source["'])(?=[^>]*\btype=["']text\/jsx["'])[^>]*>([\s\S]*?)<\/script>/i
  );

  if (!match) {
    throw new Error(`could not find <script type="text/jsx" id="app-source"> in ${html}`);
  }

  const result = babel.transformSync(match[1], {
    filename: `${html}/app-source.jsx`,
    presets: [['@babel/preset-react', { runtime: 'classic' }]],
    babelrc: false,
    configFile: false,
    sourceMaps: false,
    compact: false,
  });

  if (!result || !result.code) {
    throw new Error(`Babel produced no output for ${html}`);
  }

  const banner = `/* Generated by \`npm run build\` from ${html} #app-source — do not edit. */\n`;
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, banner + result.code + '\n', 'utf8');
  const kb = (Buffer.byteLength(banner + result.code) / 1024).toFixed(1);
  console.log(`build-app: wrote ${path.relative(root, outPath)} (${kb} KB)`);
}

let failed = false;
for (const target of targets) {
  try {
    buildOne(target);
  } catch (err) {
    console.error(`build-app: ${target.html}: ${err.message}`);
    failed = true;
  }
}
if (failed) process.exit(1);
